pipeline {
    agent any

    options {
        timestamps()
    }

    stages {
        node {
        stage('Build') {
            steps {
                withMaven {
                    sh 'mvn clean install'
                }
            }
        }
        }
    }

    post {
        always {
            junit 'build/reports/**/*.xml'
        }
    }
}
