pipeline {
    agent any

    options {
        timestamps()
    }

    tools {
        maven 'maven'
    }

    stages {
        stage('Build') {
            steps {
                dir 'catfood_control' {
                    sh 'mvn clean install'
                }
            }
        }
    }

    post {
        always {
            junit 'catfood_control/target/reports/**/*.xml'
        }
    }
}
